---
title: "Predicting drug mode of action: Random Forests"
author: "Florian Huber, Leonard Dubois"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
editor_options: 
  chunk_output_type: console
---


# Setup, library loading

This part is the general setup, whichever model we are using.

```{r setup}
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(message = T)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(error = T)
knitr::opts_chunk$set(cache = T)
Sys.setlocale("LC_ALL", "en_IE.UTF-8")

library(tidyverse)
library(mlr)

#Custom functions
walk(list.files("./R", pattern = "*.R", full.names = T), source)

library("parallelMap") #Always useful
library("parallel")

if (system('hostname', intern = TRUE) == 'spinoza.embl.de') {
   parallelStartMulticore(cpus = 10)
} else {
   parallelStartMulticore(cpus = detectCores() - 1)
}

load(file = "the_matrix.RData")
load(file = "feature_container.RData")
the_matrix = merge(x = labels, y = the_matrix, by = "drugname_typaslab", all.y = T)
```



```{r}
# try with 200 most variable genes
the_matrix_200mostvar <- the_matrix[, c("drugname_typaslab", "process_broad", 
                                   feature_container$mostvar_200)]

rf_task <- makeClassifTask(data = select(the_matrix_200mostvar, -drugname_typaslab), 
                           id = "the_matrix_200mostvar", 
                           target = "process_broad")

rf_learner <- makeLearner(cl = "classif.randomForest", 
                          predict.type = "prob")

# define hyperparameter searchspace 
treespace <- 200

# would be nice to try m = p, m = p * (3/4), m = p/2, m = p / 4m = sqrt(p)
mtryspace <- floor(c(length(feature_container$mostvar_200), 
               length(feature_container$mostvar_200) / 2, 
               sqrt(length(feature_container$mostvar_200))))

rf_paramset <- makeParamSet(
   makeDiscreteParam("ntree", treespace), 
   makeDiscreteParam("mtry", mtryspace)
)

rf_ctrl <- makeTuneControlGrid() 

# define resampling
rf_rdesc_inner <- makeResampleDesc("CV", iters = 3L, stratify = TRUE, predict = "both")
rf_desc_outer <- makeResampleDesc("RepCV", folds = 3L, reps = 3L, stratify = TRUE, predict = "both")

rf_learner_wrapped <- makeTuneWrapper(learner = rf_learner, 
                                      resampling = rf_rdesc_inner, 
                                      measures = list(mmce, timeboth), 
                                      par.set = rf_paramset, 
                                      control = rf_ctrl)


system.time(
nested_cv_res <- resample(learner = rf_learner_wrapped, 
                          task = rf_task, 
                          resampling = rf_desc_outer, 
                          models = TRUE) # or extract only selected parts using extract argument 
) # runtime 422 locally

nested_cv_res
nested_cv_res$measures.test
nested_cv_res$measures.train
nested_cv_res$models
lapply(nested_cv_res$models, getTuneResult)

parallelStop()
```



```{r}
R.version
sessionInfo()
```







