---
title: "Predicting drug mode of action: Support Vector Machine"
author: "Florian Huber, Leonard Dubois"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

# Setup, library loading

This part is the general setup, whichever model we are using.

```{r setup}
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(message = T)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(error = T)
knitr::opts_chunk$set(cache = T)
Sys.setlocale("LC_ALL", "en_IE.UTF-8")

library(tidyverse)
library(mlr)

#Custom functions
walk(list.files("./R", pattern = "*.R", full.names = T), source)

library("parallelMap") #Always useful
parallelStartMulticore(cpus = 2)

load(file = "Rep_Nest_CV.RData")

```

***

# System Vector Machine


## Setup - Loading

Learner used is `classif.svm`
On top of `mlr` package, one should also install `e1071` 

```{r }
if(!require(e1071)){
    install.packages("e1071")
}
library(e1071)
```

## Data loading

```{r}
load(file = "the_matrix_hclust.RData")
load(file = "the_matrix_top10pct.RData")
load(file = "the_matrix_top5pct.RData")
```

## Hyperparamters Tuning grid

This grid is one of the main part of the computation cost. If it can be reduced, it would be great !

```{r}

#Hyperparameter tuning
svm_hyp_param = makeParamSet(
    makeDiscreteParam("kernel", values = c("linear", "polynomial", "radial", "sigmoid")),
    makeDiscreteParam("type", values = c("C-classification")),
    makeDiscreteParam("degree", values = c(2,3,4,5))
)
   
svm_tuning = makeTuneControlGrid()
#svm_tuning = makeTuneControlRandom(maxit = 100)

```


```{r}
#Not the most relevant name, it was for some test
swag = rep_nested_CV_run(data_matrix = the_matrix_top10pct, model = "classif.svm", rep_instance = Rep_Nest_CV_instance, 
                         run_hyp_param = svm_hyp_param, run_tuning = svm_tuning, saveFeatImportance = T)


parallelStop()
```

    
***

# System and session info

```{r}
R.version
sessionInfo()
```

